param(
  [Parameter(Mandatory = $false)]
  [switch]$SkipInfisical,
  [Parameter(Mandatory = $false)]
  [string]$InfisicalEnv = "production",
  [Parameter(Mandatory = $false)]
  [string]$InfisicalProjectId = "",

  [Parameter(Mandatory = $false)]
  [string]$DeviceBootstrapKey = "",
  [Parameter(Mandatory = $false)]
  [string]$WorkerUrl = "",
  [Parameter(Mandatory = $false)]
  [string]$Timezone = "",
  [Parameter(Mandatory = $false)]
  [string]$OutFile = ""
)

$ErrorActionPreference = "Stop"

$scriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot   = Resolve-Path (Join-Path $scriptDir "..\..")
$defaultOut = Join-Path $repoRoot "firmware\src\secrets.h"
if (-not $OutFile) { $OutFile = $defaultOut }

function Resolve-InfisicalCli {
  $cmd = Get-Command infisical -ErrorAction SilentlyContinue
  if ($cmd) { return $cmd.Source }

  $defaultPath = Join-Path $env:APPDATA "npm\infisical.cmd"
  if (Test-Path $defaultPath) { return $defaultPath }

  return $null
}

$infisicalCliPath  = Resolve-InfisicalCli
$infisicalAvailable = -not [string]::IsNullOrWhiteSpace($infisicalCliPath)

if (-not $SkipInfisical -and $infisicalAvailable) {
  Write-Host "Hydrating firmware secrets from Infisical ($InfisicalEnv)..." -ForegroundColor Cyan

  $exportArgs = @("--silent", "export", "--env", $InfisicalEnv, "--format", "json")
  if ($InfisicalProjectId) { $exportArgs += @("--projectId", $InfisicalProjectId) }

  $raw  = & $infisicalCliPath @exportArgs 2>&1
  $line = ($raw | Out-String).Trim()
  if (-not $line) { throw "Infisical export returned no data." }

  $exported  = $line | ConvertFrom-Json
  $secretMap = @{}
  if ($exported -is [System.Array]) {
    foreach ($item in $exported) {
      if ($item.key -and ($null -ne $item.value)) { $secretMap[[string]$item.key] = [string]$item.value }
    }
  } else {
    foreach ($prop in $exported.PSObject.Properties) { $secretMap[[string]$prop.Name] = [string]$prop.Value }
  }

  if (-not $DeviceBootstrapKey -and $secretMap.ContainsKey("BGDISPLAY_DEFAULT_DEVICE_KEY")) { $DeviceBootstrapKey = $secretMap["BGDISPLAY_DEFAULT_DEVICE_KEY"] }
  if (-not $DeviceBootstrapKey -and $secretMap.ContainsKey("DEVICE_BOOTSTRAP_KEY"))         { $DeviceBootstrapKey = $secretMap["DEVICE_BOOTSTRAP_KEY"] }
  if (-not $WorkerUrl         -and $secretMap.ContainsKey("BGDISPLAY_DEFAULT_WORKER_URL"))   { $WorkerUrl          = $secretMap["BGDISPLAY_DEFAULT_WORKER_URL"] }
  if (-not $WorkerUrl         -and $secretMap.ContainsKey("WORKER_URL"))                     { $WorkerUrl          = $secretMap["WORKER_URL"] }
  if (-not $Timezone          -and $secretMap.ContainsKey("BGDISPLAY_DEFAULT_TIMEZONE"))     { $Timezone           = $secretMap["BGDISPLAY_DEFAULT_TIMEZONE"] }
  if (-not $Timezone          -and $secretMap.ContainsKey("TIMEZONE"))                       { $Timezone           = $secretMap["TIMEZONE"] }
} elseif (-not $SkipInfisical -and -not $infisicalAvailable) {
  Write-Host "Infisical CLI not found at $infisicalCliPath - using explicit parameters only." -ForegroundColor Yellow
}

if (-not $DeviceBootstrapKey) {
  throw "DeviceBootstrapKey is required (pass -DeviceBootstrapKey or set BGDISPLAY_DEFAULT_DEVICE_KEY in Infisical)."
}
if (-not $WorkerUrl) {
  throw "WorkerUrl is required (pass -WorkerUrl or set BGDISPLAY_DEFAULT_WORKER_URL / WORKER_URL in Infisical)."
}
if (-not $Timezone) { $Timezone = "US/Central" }

$WorkerUrl = $WorkerUrl.Trim().TrimEnd('/')

$escapedWorker   = $WorkerUrl.Replace('"', '')
$escapedDevice   = $DeviceBootstrapKey.Replace('"', '')
$escapedTimezone = $Timezone.Replace('"', '')

$lines = @(
  "#pragma once",
  "",
  "// Generated by firmware/scripts/firmware_secrets_sync.ps1 - do not edit by hand.",
  "// Re-run the script to update from Infisical.",
  "#define BGDISPLAY_DEFAULT_WORKER_URL `"$escapedWorker`"",
  "#define BGDISPLAY_DEFAULT_DEVICE_KEY `"$escapedDevice`"",
  "#define BGDISPLAY_DEFAULT_TIMEZONE `"$escapedTimezone`""
)
Set-Content -Path $OutFile -Value $lines -Encoding ascii
Write-Host "secrets.h updated: $OutFile" -ForegroundColor Green
